#!/bin/bash
#
#chkconfig: 2345 80 90
#description: mongodb
base_dir=/app/local/mongo27019
data_dir=/app/data/mongodb27019
start(){
    ${base_dir}/bin/mongod -f ${base_dir}/etc/mongodb.conf
}

stop(){
    ${base_dir}/bin/mongod -f ${base_dir}/etc/mongodb.conf --shutdown
}

restart(){
    stop
    start
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac